### PR TITLE
PHP code examples little fixes

### PR DESCRIPTION
**Pull request by matteofigus**
I issued a PR for little fixes on PHP:
* Removed the limit on the list key policy code example as discussed in #6 
* Some cleanup on not needed whitespaces for improved consistency and readability

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by seebees** [comment]
LGTM

**Comment by juneb** [comment]
These look fine to me. I'm going to grab our PHP SDK writer for a sanity check.

**Comment by jschwarzwalder** [comment]
They look great.

Thank you for your contribution.

Limit is optional parameter, but it is fine to remove.

**Comment by juneb** [comment]
Thanks, @jschwarzwalder , @seebees , and @matteofigus ! I'll merge this. 

@matteofigus , same caveat as with the other PR. It will take a few days to get this into the official docs, but you'll see it soon.

**Pull request merged**
