### PR TITLE
Update control-access-overview.md

### PR DESCRIPTION
**Pull request by Kamerabuilt**
You can control the crypto-usage (ex. Encrypt, Decrypt) of a KMS key through an IAM policy attached to a user, even without explicitly adding them as a KMS CMK Key-User, and doing so with the default (non-modified) Key-Policy that is in place. In other words, once the KMS CMK key is created through the GUI console (as well as its default Key-Policy), it is possible to assign a user or a role the IAM permissions to encrypt/decrypt data. The documentation seems to say imply that Key-Policy should allow that access, regardless of any IAM policies. 

To test: create a CMK with all the defaults, and without adding any Admin or any Key-Users. Create a new IAM user, and assign them the following: 
    "kms:Decrypt",
    "kms:DescribeKey",
    "kms:Encrypt",
    "kms:GenerateDataKey*",
    "kms:ReEncrypt*"

That IAM user would be able to encrypt data, through the CLI, even though the default Key-Policy was not modified, and even though they were never added under the Key Users section of the CMK. If this behavior is normal, I believe the documentation should be changed to reflect all of this.

### CODE REVIEW

**Comment by juneb** [comment]
Thanks so much for your contribution. You're right that this works, but this scenario is possible only because the default key policy in the console allows the account to use IAM policies. The root of trust is in the key policy. 

I'll discuss this with KMS engineers and see if we need to update the documentation. Again, thanks so much for raising the issue.

**Comment by Kamerabuilt** [comment]
Thanks for your feedback. 

The default policy in place looks like this: 

{
    "Id": "key-consolepolicy-3",
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<account_number>:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        }
    ]
}

If this bare-bone-default policy is altered, it would possibly render the entire CMK useless, meaning, at a minimum, it is needed for the CMK to function properly, and is therefore a static (and completely transparent) given. 

The main question I still have is: how come the IAM policy works by itself, with that default key policy, without even needing to add the IAM user under Key Users?  

I do understand that if we do add an IAM user under Key Users, they wont actually require to have the permissions under their IAM policy, but this would actually be very similar to allowing a principal to access an S3 bucket, without them having that access within their own IAM policy. And the opposite is true: an IAM user, with the right permissions, can access the S3 bucket, even though they are not explicitly added under the resource policy of the S3 bucket.

**Comment by juneb** [comment]
I'm going to engage the KMS engineering team on Monday. I want to make sure the answer I provide is completely correct. This is a really valuable conversation. Thanks for starting it.

**Comment by juneb** [comment]
Continuing the conversation in the related issue:  https://github.com/awsdocs/aws-kms-developer-guide/issues/29

**Comment by Kamerabuilt** [comment]
I updated issue 29 with relevant info.

**Comment by juneb** [comment]
The key policy must have a statement that allows the account to use IAM policies to control access to the CMK. Thanks again for your contribution.

**Pull request closed without merging**
