### PR TITLE
Update concepts.md

### PR DESCRIPTION
**Pull request by kravell**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by juneb** [comment]
Thanks, Kiran! Was this just one change? The file diff displays the Key Management Infrastructure description, but I don't see any changes.

**Comment by kravell** [comment]
@matteofigus 
Yes, that was the only change. I wanted to know if that is a correct statement.

**Comment by juneb** [comment]
Thanks!

**Comment by juneb** [comment]
Update: The KMS team confirmed that you can combine multiple algorithms when using envelope encryption. For example, you can use a symmetric data key to encrypt your data and an asymmetric key to encrypt the data key.

**Pull request merged**
